### ISSUE TITLE
[internal] Client project can't import @common

### ISSUE THREAD

**Issue by Jkwok0714** [TestaDiMucca/AcquaClaudia#69]
# Description

```bash
[PACKARINO] ✓ built in 1.75s
[PACKARINO] "formatMilliseconds" is not exported by "../../packages/common/build/index.js", imported by "src/components/about/StatsDisplay.vue?vue&type=script&setup=true&lang.ts".
[PACKARINO] file: /Users/admin/Documents/GitHub/Hoarder-Util/h-util-ui/client/src/components/about/StatsDisplay.vue?vue&type=script&setup=true&lang.ts:10:9
[PACKARINO]  8: import { computed } from 'vue';
[PACKARINO]  9: import { StatsStorage } from '@shared/common.types';
[PACKARINO] 10: import { formatMilliseconds } from '@common/common';
[PACKARINO]              ^
[PACKARINO] error during build:
[PACKARINO] RollupError: "formatMilliseconds" is not exported by "../../packages/common/build/index.js", imported by "src/components/about/StatsDisplay.vue?vue&type=script&setup=true&lang.ts".
[PACKARINO]     at error (file:///Users/admin/Documents/GitHub/Hoarder-Util/h-util-ui/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
[PACKARINO]     at Module.error (file:///Users/admin/Documents/GitHub/Hoarder-Util/h-util-ui/node_modules/rollup/dist/es/shared/node-entry.js:13745:16)
```

# Unknowns

Things that need to be investigated if any.

**Comment by Jkwok0714** [comment]
Copy has been made and is no longer shared - other project deprecated for now. Revive issue if other project picks up.
